//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the ASP.NET Web Forms page.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator
{
    public partial class WebForm1
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtLength;
        protected global::System.Web.UI.WebControls.CheckBox chkUpper;
        protected global::System.Web.UI.WebControls.CheckBox chkLower;
        protected global::System.Web.UI.WebControls.CheckBox chkNumber;
        protected global::System.Web.UI.WebControls.CheckBox chkSymbol;
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
    }
}
